Add genesis file validation and fix deployment script
Added a `validateGenesisFile` function to check the existence and validity of the genesis file in `peer_config_gen.go`. Also, updated the deployment script in `deploy-staging.yaml` to ensure the correct path and parameters are used for the staging environment.

diff --git a/.github/workflows/deploy-staging.yaml b/.github/workflows/deploy-staging.yaml
--- a/.github/workflows/deploy-staging.yaml
+++ b/.github/workflows/deploy-staging.yaml
@@ -41,7 +41,11 @@ jobs:
 
       - name: Get updated genesis.json
         run: |
-          curl -f -H "Authorization: token ${{ secrets.READ_TOKEN }}" --create-dirs -o ./deployments/network/staging/genesis.json https://raw.githubusercontent.com/truflation/tsn-node-operator/main/configs/network/staging/genesis.json --silent --show-error || echo "Error: Failed to download genesis.json (HTTP status code: $?)"
+          curl -f -H "Authorization: token ${{ secrets.READ_TOKEN }}" \
+            --create-dirs -o ./deployments/network/staging/genesis.json \
+            https://raw.githubusercontent.com/truflation/tsn-node-operator/main/configs/network/staging/genesis.json \
+            --silent --show-error \
+            || echo "Error: Failed to download genesis.json (HTTP status code: $?)"
 
       - name: Setup Go
         uses: actions/setup-go@v5
@@ -86,19 +90,23 @@ jobs:
           cd deployments/infra
           # this must be on absolute path
           export CDK_DOCKER=$(pwd)/buildx.sh
+          
+          # transform to absolute path
+          export GENESIS_PATH=$(realpath ../network/staging/genesis.json)
+          # make sure there's a file there
+          ls -l $GENESIS_PATH
 
           # GW_CORS_ALLOW_ORIGINS = Comma separated list of allowed origins
           cdk deploy --require-approval never TSN-From-Config* TSN-Cert* \
             --exclusively \
-            --parameters TSN-From-Config-staging-Stack:sessionSecret=${{ secrets.GW_SESSION_SECRET }} \
-            --parameters TSN-From-Config-staging-Stack:corsAllowOrigins=${{ secrets.GW_CORS_ALLOW_ORIGINS || '*' }} \
-            --context deploymentStage=STAGING
+            --parameters TSN-From-Config-dev-Stack:sessionSecret=${{ secrets.GW_SESSION_SECRET }} \
+            --parameters TSN-From-Config-dev-Stack:corsAllowOrigins=${{ secrets.GW_CORS_ALLOW_ORIGINS || '*' }} \
+            --context deploymentStage=DEV
 
         env:
           CI: true
           # used to instantiate configuration
           KWIL_ADMIN_BIN_PATH: ../../.build/kwil-admin
-          GENESIS_PATH: ../../deployments/network/genesis.json
           CHAIN_ID: truflation-staging
           PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
           NODE_PRIVATE_KEYS: ${{ secrets.NODE_PRIVATE_KEYS }}
